### ISSUE TITLE
Plex integration not working

### ISSUE THREAD

**Issue by nickisagod** [styxit/HTPC-Manager#364]
Hi, I am new to HTPC however i cannot setup Plex integration. please see the logs below - 

2015-12-07 21:09:33	modules.plex	ERROR	Unable to contact Plex via http://192.168.0.4:32400 error HTTP Error 401: Unauthorized

Any help would be greatly appreciated as I have everything else working perfect and it seems to be the perfect solution.
Thanks in advance, Nick

**Comment by joemcmonagle** [comment]
Nick,
Any chance you can share the fix for this error? I'm having the same issue.

/J

**Comment by Hellowlol** [comment]
using ssl?

**Comment by nickisagod** [comment]
J

I ended up using a different fork (the hellowlol one) as this had the sonarr integration I wanted as well. Plex setup was fine with it. Sorry I know that's not a lot of help. Worth throwing a question on reddit.com/r/plex as they can answer most things straight off.

**Comment by Hellowlol** [comment]
Alright, im glad you got it sorted.

**Comment by joemcmonagle** [comment]
Thanks Nick. I'm currently on the master2 branch. I have Plex configured with Preferred SSL and HTPC configured with no SSL. I have plex configured with a letsencrypt cert. I'm seeing the same error as in Nick's original post

**Comment by Hellowlol** [comment]
Since you are refering to my fork, please read the issue guidelines and open a new issue on my fork.

**Comment by MattTwinkleToes** [comment]
the problem is that is the url that it tries is incomplete, it requires a plex token, without one plex returns 404 unauthorised.  I have tried to trick htpc manager into sending the complete string but because there is no configuration option to include the plex token it just adds status/sessions at the end of everything.

http://pmsip:32400/status/sessions

should be 


http://pmsip:32400/status/sessions?X-Plex-Token=yourtokenhere

How frustrating!  I dont want to go into he scripts and hack away at them to get this to work.
